name: MLflow CI & Docker Workflow

on:
  push:
    branches:
      - main

jobs:
  retrain-and-artifact:
    runs-on: ubuntu-latest
    # Gunakan login shell agar conda dapat diinisialisasi dengan benar
    defaults:
      run:
        shell: bash -l {0}
    steps:
      # Langkah 1: Checkout kode dari repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Langkah 2: Setup environment Conda
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: '3.10'

      # Langkah 3: Install MLflow di environment dasar agar bisa menjalankan perintah 'mlflow'
      - name: Install MLflow
        run: pip install mlflow

      # Langkah 4: Jalankan MLflow Project. 
      # MLflow akan otomatis membuat environment dari conda.yaml dan menjalankan skrip
      - name: Run MLflow Project
        run: mlflow run ./MLProject

      # Langkah 5: Simpan Artefak ke GitHub
      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mlflow-artifacts
          path: mlruns/

  build-and-push-docker:
    needs: retrain-and-artifact # Jalankan job ini setelah job pertama selesai
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Langkah untuk login ke Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Langkah untuk build dan push image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./MLProject # Direktori yang berisi Dockerfile
          push: true
          tags: makiatulmsyr17/heart-disease-app:latest # Ganti dengan username/nama_repo Anda