name: MLflow CI & Docker Workflow

on:
  push:
    branches:
      - main

jobs:
  retrain-and-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install mlflow pandas scikit-learn
      - name: Run MLflow Project
        run: mlflow run ./MLProject
      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mlflow-artifacts
          path: mlruns/

  build-and-push-docker:
    needs: retrain-and-artifact # Jalankan job ini setelah job pertama selesai
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Langkah untuk login ke Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Langkah untuk build dan push image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./MLProject # Direktori yang berisi Dockerfile
          push: true
          tags: makiatulmsyr17/heart-disease-app:latest # Ganti dengan username/nama_repo Anda
